# Working with 3D data

Imagine you have 3d data-sets, e.g.

In [6]:
import numpy as np

data = np.random.randn(4,3)
data_2 = np.eye(3)
data_2 = np.vstack((data_2, [1, 1, 0]))

print(data)
print(data_2)

[[-0.96675054  0.84677435 -0.00683761]
 [ 0.45177519  0.40162324 -0.85813154]
 [ 3.17879677 -0.58454589  0.43701946]
 [ 0.88249877  0.98248283 -0.70609389]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

## Voluntary Exercise
If you can perform the following tasks, the next exercise will be easy for you:

* Try abc to find an efficient way to translate these data by [0, 10, 100]
* Try to create a 1-D column vector with the values [0, 10, 100, 1000], and add it to these data
* How can you rotate these data by 10 deg around the y-axis? And what does that mean, e.g. for the vectors [1, 0, 0], and [1, 1, 0]?
* Using one line of code, and scikit-kinematics, can you project the vector [5, 2, 4] into the plane perpendicular to [1, 0, 1]? Can you also draw a diagram for that taks?

### Hints

* Check out https://numpy.org/doc/stable/user/basics.broadcasting.html
* A vector $\vec{x} = \begin{pmatrix}
1\\
2\\
3\\
\end{pmatrix}$ can be rotated by $\vec{x}' = \mathbb{R} * \vec{x}$

In [11]:
import skinematics as skin
Rx = skin.rotmat.R('x', 10)
print(Rx)

[[ 1.          0.          0.        ]
 [ 0.          0.98480775 -0.17364818]
 [ 0.          0.17364818  0.98480775]]
